on:
  pull_request:
  push:
    branches: [trunk]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotlessLint:
    name: Linting via Spotless Gradle Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: spotlessCheck task
        run: ./gradlew spotlessCheck